from urllib.parse import urlparse

TRUSTED_DOMAINS = frozenset({
    # My domains
    "broryat.tech",
    # Big tech
    "google.com",
    "microsoft.com",
    "apple.com",
    "amazon.com",
    "ibm.com",
    "oracle.com",
    "adobe.com",
    "salesforce.com",
    "cloudflare.com",
    "samsung.com",
    "sony.com",
    "intel.com",
    "nvidia.com",
    "dell.com",
    "hp.com",
    # AI companies & assistants
    "openai.com",
    "chatgpt.com",
    "anthropic.com",
    "claude.ai",
    "deepmind.com",
    "deepseek.com",
    "perplexity.ai",
    "midjourney.com",
    "huggingface.co",
    "mistral.ai",
    "cohere.com",
    "x.ai",
    "grok.com",
    "bing.com",
    "copilot.microsoft.com",
    # Social media & messaging
    "facebook.com",
    "instagram.com",
    "whatsapp.com",
    "telegram.org",
    "twitter.com",
    "x.com",
    "linkedin.com",
    "tiktok.com",
    "youtube.com",
    "snapchat.com",
    "reddit.com",
    "pinterest.com",
    "discord.com",
    "line.me",
    "wechat.com",
    "kakao.com",
    "naver.com",
    "viber.com",
    "zoom.us",
    "slack.com",
    "skype.com",
    # Dev/cloud platforms
    "github.com",
    "gitlab.com",
    "stackoverflow.com",
    "dropbox.com",
    "digitalocean.com",
    "vercel.com",
    "render.com",
    "netlify.com",
    "heroku.com",
    "atlassian.com",
    "notion.so",
    "figma.com",
    # E-commerce & payments
    "paypal.com",
    "visa.com",
    "mastercard.com",
    "ebay.com",
    "alibaba.com",
    "aliexpress.com",
    "shopify.com",
    "walmart.com",
    "target.com",
    "stripe.com",
    "wise.com",
    "revolut.com",
    "booking.com",
    "airbnb.com",
    "grab.com",
    # Entertainment & streaming
    "netflix.com",
    "spotify.com",
    "disneyplus.com",
    "twitch.tv",
    # News & reference
    "wikipedia.org",
    "bbc.com",
    "cnn.com",
    "reuters.com",
    "nytimes.com",
    # Email & productivity
    "outlook.com",
    "yahoo.com",
    "protonmail.com",
    "icloud.com",
    # Cambodia government, banks, telecoms, universities
    "gov.kh",
    "moh.gov.kh",
    "mef.gov.kh",
    "mfaic.gov.kh",
    "nbc.gov.kh",
    "mptc.gov.kh",
    "mot.gov.kh",
    "acledabank.com.kh",
    "ababank.com",
    "canadiabank.com.kh",
    "wingbank.com.kh",
    "smart.com.kh",
    "cellcard.com.kh",
    "metfone.com.kh",
    "rupp.edu.kh",
    "itc.edu.kh",
})


def is_trusted_domain(url: str) -> bool:
    normalized = url if "://" in url else f"https://{url}"
    host = urlparse(normalized).netloc.lower()
    labels = host.split(".")

    return any(".".join(labels[i:]) in TRUSTED_DOMAINS for i in range(len(labels)))
